
#THIS MANIFEST FILE IS USED BY DEMO-BUILD-DEPLOY-V1.YML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment-v2
  namespace: demo-eche
spec:
  selector:
    matchLabels:
      app: demoapp-v2
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: demoapp-v2
    spec:
      containers:
      - name: demoapp-v2
        #image: $DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_SHA 
        #image: '${{secrets.DOCKERHUB_USERNAME}}/demo_hello_world_deploy:${{github.sha}}'
        #
        #Naming convention that uses environment variables, so values can be updated
        image: __DOCKER_REPOSITORY__/__IMAGE_NAME__:__IMAGE_TAG__
        #
        #$DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_RUN_NUMBER
        ports:
        - containerPort: 80