#This workflow is triggered on a push to github branch che
name: demo_multi_build
on:
  push:
    branches:
      - echemultiplatform     

jobs:

  build-multi-platform:
    runs-on: ubuntu-latest
    env:
      #Environment variables for Docker image
#      DOCKER_REPOSITORY: eche21 # name of Docker Hub ID
      IMAGE_NAME: eche21/demoappv3 # name of image
     #

    steps:
#    
    - name: Git checkout
      uses: actions/checkout@v3
#  
    - name: Set image tag
      run: echo "COMMIT_SHA=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD}}
    - name: Build and push image
      uses: docker/build-push-action@v3
      with:
          context: ./app
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.COMMIT_SHA }}
