name: demo_build_and_deploy_aks

on:
  push:
    branches:
      - che      
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: eche21 # name of Docker Hub ID
      IMAGE_NAME: demoapp
      IMAGE_TAG: ${{ github.run_number }} # $GITHUB_RUN_NUMBER
      
      CLUSTER_NAME: RegScale
      CLUSTER_RESOURCE_GROUP: Corporate
      NAMESPACE: demo-eche
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    #- name: Setup .NET Core SDK
    #  uses: actions/setup-dotnet@v1.5.0
    #  with:
    #    # SDK version to use. Examples: 2.2.104, 3.1, 3.1.x
    #    dotnet-version: 3.1.x
        # Optional package source for which to set up authentication. Will consult any existing NuGet.config in the root of the repo and provide a temporary NuGet.config using the NUGET_AUTH_TOKEN environment variable as a ClearTextPassword
    #- name: dotnet build
    #  run: dotnet build -c release
    
    #
#
    - name: docker build
#      run: docker build -t demo_hello_world_deploy:'${{github.sha}}' .
      run:     docker build ./app/ --file ./app/Dockerfile --tag demoimage #:'${{github.sha}}'     

    - name: docker login
      run: docker login --username '${{secrets.DOCKERHUB_USERNAME}}' --password '${{secrets.DOCKERHUB_PASSWORD}}'
      
    - name: tag docker image
      run: docker tag demoimage '${{secrets.DOCKERHUB_USERNAME}}'/demo:'${{github.sha}}'
    
    - name: push docker image
      run: docker push '${{secrets.DOCKERHUB_USERNAME}}'/demo:'${{github.sha}}'