name: demo_build_and_deploy_aks_v1

on:
  push:
    branches:
      - che      
variables:
  tag: test

stages:
- stage: Build
  jobs: 
  - job: Build_Push_Image
    pool:
      vmImage: 'ubuntu-latest'
    steps:

      - script: echo "##vso[task.setvariable variable=commit-tag;isOutput=true]$(echo $BUILD_SOURCEVERSION | cut -c 1-7)"
        name: setCommitTag
        displayName: 'Set Commit Tag'

      - script: echo Commit tag is $(setCommitTag.commit-tag)
        displayName: 'Display Commit Tag'

      - task: Docker@2
        displayName: 'Build Image and Push to ACR'
        inputs:
          containerRegistry: 'eche21'
          repository: 'demo'
          command: 'buildAndPush'
          Dockerfile: './app/Dockerfile'
          tags: |
            $(setCommitTag.commit-tag)
  - job: Update_Vars
    displayName: Update_Vars
    pool:
      name: 'demo Build Push'
    dependsOn: ['Build_Push_Image']
    variables:
      commit-tag: $[ dependencies.Build_Push_Image.outputs['setCommitTag.commit-tag'] ]
    steps:
    - script: echo Commit Tag is $(commit-tag)
      displayName: 'Show Commit Tag'
    
    - task: variableupdater@1
      inputs:
        VariableGroupId: '3'
        VariableName: 'DEMO_SHA'
        NewValue: '$(commit-tag)'